(function(g){var window=this;'use strict';var Y3=function(a){a.oa("cardstatechange",a.Ik()&&a.gp()?1:0)},Z3=function(a,b){var c=g.Ya(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},skb=function(a){var b=g.fs(a);
a=g.is(a);return new g.Vr(b.x,b.y,a.width,a.height)},tkb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.OC(a,b,function(){g.PC(e);c.apply(a,arguments)},d)},b4=function(a){a=g.db(a);
delete $3[a];g.id($3)&&a4&&a4.stop()},vkb=function(){a4||(a4=new g.Eu(function(){ukb()},20));
var a=a4;a.isActive()||a.start()},ukb=function(){var a=g.gb();
g.Wc($3,function(b){wkb(b,a)});
g.id($3)||vkb()},c4=function(a,b,c,d){g.Yu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},wkb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;xkb(a,a.progress);1==a.progress?(a.j=0,b4(a),a.onFinish(),a.wr()):a.isPlaying()&&a.qL()},xkb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},ykb=function(a,b){g.yb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},d4=function(a,b,c,d,e){c4.call(this,b,c,d,e);
this.element=a},zkb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
d4.call(this,a,b,c,d,e)},Akb=function(a){return Math.pow(a,3)},Bkb=function(a){return 3*a*a-2*a*a*a},Ckb=function(a){g.H.call(this);
this.B=a||window;this.j=[]},e4=function(a){return a.baseUrl||null},f4=function(a,b){return g.bt(g.pr(a,b),function(c){return!!c})},Dkb=function(a,b,c){function d(ta){var la=ta.hovercardButton;
if(!la)return null;la=la.subscribeButtonRenderer;if(!la)return null;var qa=f(la.unsubscribedButtonText),ba=f(la.subscribedButtonText);if(la.subscribed){var T=f(la.subscriberCountWithUnsubscribeText);var Ma=f(la.subscriberCountText)}else T=f(la.subscriberCountText),Ma=f(la.subscriberCountWithSubscribeText);var y=null;if(ta.signinEndpoint){y=Z3(ta,"signinEndpoint","webNavigationEndpointData","url");if(!y){var Z,Ua;y=null==(Ua=g.R(null==(Z=la.signInEndpoint)?void 0:Z.commandMetadata,g.Q2))?void 0:Ua.url}if(!y)return null}return qa&&
(ba||y)?{subscribed:la.subscribed,subscribeText:qa,subscribeCount:T,unsubscribeText:ba,unsubscribeCount:Ma,enabled:la.enabled,signinUrl:y,classic:ta.useClassicSubscribeButton}:null}
function e(ta){if(ta){var la=[],qa=ta.videoId;qa&&la.push("v="+qa);(qa=ta.playlistId)&&la.push("list="+qa);(ta=ta.startTimeSeconds)&&la.push("t="+ta);return"/watch?"+la.join("&")}}
function f(ta){if(!ta)return null;var la=ta.simpleText;return la?la:ta.runs?g.pr(ta.runs,function(qa){return qa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,B=null,F=null,G=null,I=null,L=null,P=null;if("VIDEO"===h)g.R(l,g.zG)?m=g.R(l,g.zG).url:(P=g.R(l,g.yT),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.R(l,g.zG)?m=g.R(l,g.zG).url:(P=g.R(l,g.yT),m=e(P)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=Z3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=Z3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=Z3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=Z3(b,"title","accessibility","accessibilityData","label");var V=b.endpoint?b.endpoint.clickTrackingParams:null,
ka="";if(b.metadata){var sa=f(b.metadata);sa&&(ka=sa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ka,callToAction:f(b.callToAction),FV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,ZD:p,playlistLength:t,channelId:v,subscribeButton:B,subscribersText:F,isSubscribe:x,targetUrl:m||null,u7:n,sessionData:V?{itct:V}:null,Nba:q,FC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:f4(b.impressionUrls||[],e4),i7:f4(b.hovercardShowUrls||[],e4),clickUrls:f4(l.loggingUrls||[],e4),visualElement:g.FF(b.trackingParams),productPrice:I,additionalFeesText:L,watchEndpoint:P||null}},Ekb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:f4(a.impressionUrls||[],e4),elements:f4(a.elements||[],function(d,e){return Dkb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.FF(a.trackingParams));return c},Fkb=function(a){g.RV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.W=!0;this.K=0;a=a.U();this.Z=g.rS(a)||g.tS(a);this.events=new g.aL(this);g.J(this,this.events);this.events.T(this.player,g.kK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.lK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Zb);this.events.T(window,"focus",this.W$);this.load();var b=g.$e("STYLE");(g.Je("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.nf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Gkb=function(a){return a.player.getVideoData().Gf?"current":a.Z?"new":"current"},g4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Hkb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Ekb(f,Gkb(a))));h4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Ix;d&&(c.postParams={ad_tracking:d});if(b=g.cSa(b))if(b=g.Jn(b),b=g.Vd(b))a.C=g.fC(b,c)},h4=function(a,b,c){c=void 0===c?!0:c;
a.player.wf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Ikb(a);c=[];d=new g.jK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.GU(a.player,a.B.element,4),a.D=new g.MG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Jkb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.GU(a.player,f.element,4);var h=new g.jK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Kkb(a,f,e)}else g.LF(new g.eD("buildEndscreenElement null",
e))}a.player.Af(c);a.Zb()}},Ikb=function(a){var b=g.GF(),c=g.HF();
c&&b&&a.endscreen.visualElement&&g.OB(g.TF)(void 0,c,b,a.endscreen.visualElement)},Jkb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.FC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:i4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:j4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.cv(b.title||"")},ya:b.title},{I:"div",S:b.ZD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.FC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:i4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:j4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.cv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.FC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:j4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.cv(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:i4(b)}]};c=new g.U(c);var d=g.Ke(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Mu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.yW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.FC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",Y:{dir:g.cv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:j4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:i4(b)},{I:"div",S:"ytp-ce-expanding-icon",Y:Lkb(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.FC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.cv(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:j4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:i4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.Mu(c.element,"ytp-ce-placeholder");return c},i4=function(a){if(a.FV)var b=a.FV.thumbnails;
return Lkb(b?b[b.length-1].url:null)},Lkb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Kkb=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Mu(b.element,"ytp-ce-force-expand"),k4(a,c.id,!0)):(g.Ou(b.element,"ytp-ce-force-expand"),g.Ou(b.element,"ytp-ce-element-hover"),k4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){Mkb(a,b,c)});
b.Ra("mouseleave",function(){Nkb(a,b,c)});
a.player.U().B||b.Ra("click",function(){g.Mu(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){Okb(a,c,m)});
b.Ra("keypress",function(m){Okb(a,c,m)});
b.Ra("focus",function(){Mkb(a,b,c)});
b.Ra("blur",function(){Nkb(a,b,c)});
b.Ra("touchstart",function(){Mkb(a,b,c)});
var l=g.Me("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Ou(b.element,"ytp-ce-element-hover");g.Ou(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.Me("ytp-sb-subscribe",b.element));d(g.Me("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},Okb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Lu(d,"ytp-ce-element");){g.Lu(d,"subscribe-label")&&Pkb(a,b);
if(g.Lu(d,"ytp-ce-channel-subscribe"))return;d=g.of(d)}if(!d||g.Lu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Nkb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Nba)Pkb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jn(j4(a,b.targetUrl)),g.nH(g.Vd(c),void 0,b.sessionData);else{var e=g.BS(a.player.U())||a.player.getVideoData().Gf,f=function(){var h=j4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.TB(h);e&&n&&(n.v||
n.list)?a.player.Io(n.v,l,n.list,!1,void 0,m||void 0):g.xwa(h,l)};
Pkb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},j4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.IS(a)+b}else return"";return b},Mkb=function(a,b,c){g.Lu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Mu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Eu(function(){g.Mu(b.element,"ytp-ce-element-hover")},200)).start():g.Mu(b.element,"ytp-ce-element-hover"),l4(a,c.i7),k4(a,c.id,!0))},Nkb=function(a,b,c){g.Ou(b.element,"ytp-ce-element-hover");
g.Ou(b.element,"ytp-ce-force-expand");k4(a,c.id,!1)},k4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Qu(a.j[e].element,"ytp-ce-element-shadow-show",c)},l4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||g4(a))c&&c();else{b=Qkb(a,b);var e=0,f=!1,h=new g.Eu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.yE(b[a],d)}},Pkb=function(a,b,c){l4(a,b.clickUrls,c);
(a=g.HF())&&b.u7&&g.$F(a,b.visualElement)},Qkb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Rkb(b[d],c));return a},Rkb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Skb=function(a){return"string"===typeof a?a:""},m4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Tkb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},n4=function(a){return a.value?a.value:null},o4=function(a){if(!a)return null;
var b=g.Jn(Skb(a.value));b=g.Vd(b);if(!b)return null;var c=m4(a.target,Ukb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Tkb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Vkb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Ykb=function(a){if(!a)return null;
var b=m4(a.type,Wkb),c=m4(a.trigger,Xkb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=o4(a?a:null);return b?new Vkb(b,c,a):null},Zkb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},$kb=function(a,b){return g.Db(a.action,b)},alb=function(a,b){this.context=a;
this.j=b},blb=function(a){return a.customMessage?p4("div","iv-card-message",a.customMessage):""},q4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",Y:{style:a},V:c}},clb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(p4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},p4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.cv(c);return{I:a,Y:b,ya:c}},dlb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.OC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.OC+");");c.dir=g.cv(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,Y:c,V:d}},r4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.dj.click,5)}},elb=function(a,b){this.merchant=a;
this.price=b},flb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},glb=function(a,b){return b?b:flb(a)?"current":"new"},s4=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Xa=new Map;this.Za=new Map;this.context.J.addEventListener(g.kK("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.lK("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},t4=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.rL(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.rb=!1});
a.context.j.Ra(b,"touchmove",function(){a.rb=!0})},hlb=function(a){var b;
return(null==(b=g.R(a,g.zG))?0:b.url)?g.R(a,g.zG).url:(a=g.R(a,g.yT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},u4=function(a,b,c){return{fX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
H_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
KK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},ilb=function(a,b,c){s4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Bb=this.Na=this.Rb=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.Z=this.La=this.G=this.Va=this.j=null;this.ma=[];this.ra=this.N=this.Ef=this.Ga=null;this.K=0;this.Ea=new g.Eu(function(){},c.X.wl?4E3:3E3);
g.J(this,this.Ea);this.kb=new g.Eu(function(){});
g.J(this,this.kb);this.Ba=new alb(c,function(e,f,h,l,m,n){t4(d,e,f,h,l,m,n)});
this.W=new g.U({I:"div",S:"iv-drawer",Y:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.J(this,this.W);this.D=this.W.element;this.bb=new g.MG(this.W,330);g.J(this,this.bb);this.Jb=g.Me("iv-drawer-header-text",this.D);this.B=g.Me("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&v4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.C)&&w4(d)});
this.Qa=new g.aL(this);g.J(this,this.Qa);this.J.addEventListener("videodatachange",this.jt.bind(this))},jlb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){v4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){w4(a)});
var c=b.headerText;g.qf(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.FF(b.trackingParams);a.N=g.FF(b.closeTrackingParams);a.Ef=g.FF(b.iconTrackingParams)},klb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,dj:{},ip:null,Lj:e.trackingParams?g.FF(e.trackingParams):null,Ef:f&&f.trackingParams?g.FF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
OC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};x4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:y4(a,c,b,f),sponsored:!1,dj:u4(f,e,f.command),ip:f.trackingParams?g.FF(f.trackingParams):null,Lj:e.trackingParams?g.FF(e.trackingParams):null,Ef:l&&l.trackingParams?g.FF(l.trackingParams):null,imageUrl:z4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.nG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,OC:null,title:f.title?g.nG(f.title):"",customMessage:f.callToAction?g.nG(f.callToAction):"",url:g.R(f.command,g.zG).url?o4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.zG).url}):null,onClickCommand:null};x4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.nG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,dj:u4(e,f,e.endpoint),ip:e.trackingParams?g.FF(e.trackingParams):null,Lj:f.trackingParams?g.FF(f.trackingParams):null,Ef:l&&l.trackingParams?g.FF(l.trackingParams):null,channelId:g.R(e.endpoint,g.dV).browseId,customMessage:e.customText?g.nG(e.customText):null,profileImageUrl:z4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.nG(e.channelName):"",metaInfo:[e.subscriberCountText?g.nG(e.subscriberCountText):""],url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,g.dV).canonicalBaseUrl?g.R(e.endpoint,g.dV).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,g.dV).browseId}),onClickCommand:null};x4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.nG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,dj:u4(e,f,e.action),ip:e.trackingParams?g.FF(e.trackingParams):null,Lj:f.trackingParams?g.FF(f.trackingParams):null,Ef:l&&l.trackingParams?g.FF(l.trackingParams):null,XF:z4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.nG(e.customMessage):null,playlistVideoCount:g.nG(e.playlistVideoCount),title:e.playlistTitle?g.nG(e.playlistTitle):"",metaInfo:[e.channelName?g.nG(e.channelName):
"",e.videoCountText?g.nG(e.videoCountText):""],url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:hlb(e.action)}),onClickCommand:null};x4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.nG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,dj:u4(e,f,e.action),ip:e.trackingParams?g.FF(e.trackingParams):null,Lj:f.trackingParams?g.FF(f.trackingParams):null,Ef:l&&l.trackingParams?g.FF(l.trackingParams):null,XF:z4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.nG(e.lengthString):null,customMessage:e.customMessage?g.nG(e.customMessage):null,title:e.videoTitle?g.nG(e.videoTitle):"",metaInfo:[e.channelName?g.nG(e.channelName):
"",e.viewCountText?g.nG(e.viewCountText):""],isLiveNow:!!e.badge,url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:hlb(e.action)}),onClickCommand:null};x4(a,b)}}}}}a.K++},z4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},y4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},mlb=function(a,b){if(b=llb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.eg.id),g.nf(b.HM),g.Hb(a.cards,b),a.WG(),A4(a)},v4=function(a,b,c){if(!a.C){a.bb.show();
a.Va=new g.Eu(function(){g.Mu(a.context.J.getRootNode(),g.cZ.IV_DRAWER_OPEN)},0);
a.Va.start();a.Qa.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.HF();d&&a.Ga&&a.N&&g.YF(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.VX||(f.VX=!0,nlb(a.context.logger,f.eg.dj.fX,b)),d&&g.YF(d,[f.eg.ip]);Y3(a.J);c&&(a.G=new g.Eu(function(){a.La=a.Z;a.tb.focus()},330),a.G.start())}},w4=function(a){a.C&&(a.bb.hide(),g.UC(a.Qa),g.Ou(a.context.J.getRootNode(),g.cZ.IV_DRAWER_OPEN),a.C=!1,Y3(a.J),a.G&&a.G.stop(),a.G=new g.Eu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},plb=function(a){g.Nu(a.Fb(),
[g.cZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.GU(a.J,a.D,5);olb(a);a.Z=g.Me("ytp-cards-button",a.J.getRootNode());a.tb=g.Me("iv-drawer-close-button",a.D);a.isInitialized=!0},olb=function(a){var b=g.Me("iv-drawer-close-button",a.D);
a.context.j.Ra(b,"click",a.W4,a);a.context.j.Ra(a.B,"touchend",function(){a.Ea.start()});
a.context.j.Ra(a.B,"scroll",a.t5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Lu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.ME("iv-button-shown",a.K7,a));a.ma.push(g.ME("iv-button-hidden",a.J7,a));qlb(a)},qlb=function(a){a.ma.push(g.ME("iv-teaser-shown",a.C1,a));
a.ma.push(g.ME("iv-teaser-hidden",a.L7,a));a.ma.push(g.ME("iv-teaser-clicked",a.B1,a));a.Bb=!0},rlb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.R(b.onClickCommand,g.Sgb))?void 0:c.targetId)?(a.ra=b,!0):!1},slb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.BQa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.R(h[0],g.JZa))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},x4=function(a,b){if(!rlb(a,b)||slb(a,b)){var c=tlb(a,b);
if(c){var d={eg:b,HM:c.element,VX:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Bb||qlb(a),mlb(a,b.id),c=ulb(a,d),g.Nb(a.cards,c,0,d));else{a.isInitialized||plb(a);mlb(a,b.id);var e=ulb(a,d);g.Nb(a.cards,e,0,d);c.Ja(a.B,e);a.WG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,A4(a),vlb(a,d),v4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&wlb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){wlb(a,
d)}),A4(a))}}},tlb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=dlb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",Y:{href:b.url?n4(b.url)||"":""},V:[q4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[p4("h2",void 0,b.title),d]}]}]};c=new g.U(c);r4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],Y:{href:n4(b.url)||"","data-ytid":b.channelId},V:[q4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[blb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},clb(b)]}]}]};c=new g.U(c);r4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",Y:{href:n4(b.url)||""},V:[q4(b.XF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[blb(b),p4("h2","iv-card-primary-link",b.title),clb(b)]}]}]};
c=new g.U(c);r4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=dlb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?n4(b.url)||"":"";c={I:"div",Ma:c,Y:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",Y:{href:e},V:[p4("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.$e("span");g.qf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Yd(d,"adInfo");r4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:n4(c))||""},V:[q4(b.XF,d),{I:"div",S:"iv-card-content",V:[blb(b),p4("h2","iv-card-primary-link",b.title),clb(b),f]}]}]};c=new g.U(e);r4(a,g.Le("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},ulb=function(a,b){if(0===a.cards.length)return 0;
a=g.Eb(a.cards,function(c){return b.eg.startMs>c.eg.startMs||b.eg.startMs===c.eg.startMs&&b.eg.timestamp>=c.eg.timestamp?!0:!1});
return-1===a?0:a+1},xlb=function(a){if(a.j)return"productListing"===a.j.eg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.qr(a.cards,function(c){return"productListing"===c.eg.type})}return g.qr(a.cards,function(c){return"productListing"===c.eg.type})},A4=function(a){g.Qu(a.J.getRootNode(),"ytp-cards-shopping-active",xlb(a))},wlb=function(a,b){if(!g.Lu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.HF(),d=a.j?a.j.eg.Ef:a.Ef;
c&&d&&g.ZF(c,[d]);a.j=b;A4(a)}(c=a.isInitialized&&"none"==a.Fb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.eg.teaserDurationMs&&a.J.nB(!0,{teaserText:b.eg.teaserText,durationMs:b.eg.teaserDurationMs,onClickCommand:b.eg.onClickCommand});a.kb.isActive()||((!a.C||!a.Ea.isActive()&&a.Na)&&vlb(a,b),a.kb.start(910+b.eg.teaserDurationMs))}},vlb=function(a,b){a.W.Ib?(b=new c4([0,
a.B.scrollTop],[0,b.HM.offsetTop],600,Bkb),a.context.C.Ra(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ra(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.jG(a.W,!0),a.B.scrollTop=b.HM.offsetTop,g.jG(a.W,!1))},B4=function(a){return a.j&&a.j.eg?a.j.eg:a.cards[0]&&a.cards[0].eg?a.cards[0].eg:null},llb=function(a,b){return g.Db(a.cards,function(c){return c.eg.id===b})},C4=function(a,b,c){s4.call(this,a,b);
this.annotation=c;this.isActive=!1},ylb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},D4=function(a,b,c){C4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},zlb=function(a,b){var c=void 0===c?0:c;
var d=skb(b).width;g.ds(b,d);c=new zkb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Akb);g.J(a,c);a.context.C.Ra(c,"begin",function(){g.js(b,!0)});
c.play()},Clb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.yW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.js(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Yr(l,"right",b.image_width+"px");g.kf(a.Fb(),l);a.C=new g.Eu(function(){Alb(a,h,l)},500);
g.J(a,a.C);a.context.j.Ra(a.Fb(),"mouseover",function(){Blb(a,h,l,f,b.image_height)});
a.context.j.Ra(a.Fb(),"mouseout",function(){a.C.start()})}},Blb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.is(b);a.j||(b.style.width=g.cs(f.width,!0),c.style.width=g.cs(f.width,!0));g.Yr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Yr(d,"right","1px");a.D=!0;g.js(b,!0);a.G=new g.Eu(function(){g.Mu(this.Fb(),"iv-branding-active")},0,a);
a.G.start()}},Alb=function(a,b,c){g.Ou(a.Fb(),"iv-branding-active");
a.K=new g.Eu(function(){g.js(b,!1);a.j||(c.style.width=g.cs(0,!0))},250);
a.K.start();a.D=!1},Dlb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Elb=function(a,b,c){C4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.W=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Eu(function(){d.j.setAttribute("aria-hidden","true");g.js(d.C,!1);g.js(d.B,!0)},700,this);
g.J(this,this.G)},Hlb=function(a,b,c){c.stopPropagation();
Flb(a);Glb(a,b);a.j.focus()},Ilb=function(a){a.isCollapsed||a.Z||a.D||(g.Mu(a.Fb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Flb=function(a){a.G.stop();
a.isCollapsed&&(g.Pu(a.Fb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.js(a.B,!1),g.js(a.C,!0))},Glb=function(a,b){a.D||(a.D=g.ag(function(){Jlb(this);
Ilb(this)},b,a))},Jlb=function(a){a.D&&(g.Qa.clearTimeout(a.D),a.D=null)},Klb=function(a){this.J=a},nlb=function(a,b,c){b&&(c?E4(a,b.map(function(d){return g.tu(d,c)})):E4(a,b))},E4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.yE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Llb=function(a){g.RV.call(this,a);
var b=this;this.W=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Klb(this.player);this.D=new g.aL(this);this.G=this.vx=null;this.events=new g.aL(this);this.Sg=this.Z=this.j=null;this.ma=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.D1,this);this.subscribe("resize",this.yJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.fZ,this);g.J(this,this.events);this.ra=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.B);g.GU(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ma:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.ra);this.C.element.appendChild(a);this.mu()&&this.load();var c=this.createElement({I:"style"});(g.Je("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.nf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Mlb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.js(a,!1);return a},Nlb=function(a,b){b=!b.isCued()&&!g.TG(b,1024);
g.jG(a.B,b);g.jG(a.C,b)},Olb=function(a,b,c){a.N=!0;
a.G=g.fC(b,c)},Plb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.$a(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Plb(a,e))}return c},Tlb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.$B(h)&&h.responseXML?h.responseXML:null)&&Qlb(a,h)}};
g.mD()&&(d.onFinish=Rlb(a,d.onFinish));d.postParams={ic_only:"1"};Slb(d,c);a.N=!0;g.fC(b.Xa,d)}}},Slb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.bH&&(a.postParams.ic_coll=b.bH);b.IM&&(a.postParams.ic_xml=b.IM);b.PK&&(a.postParams.ic_track=b.PK)},Ulb=function(a){var b=new g.U({I:"div"});
g.js(b.element,!1);var c=new ilb(a.player,b.element,F4(a));g.J(c,b);b.Ja(a.B.element);c.KF();return c},Wlb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.W=!0,Vlb(a,b),b.headerText&&a.Sg&&(c=g.nG(b.headerText),a.Sg.setAttribute("title",c))},F4=function(a){if(!a.Z){var b=new Ckb(a);
g.J(a,b);var c=new g.cp(a);g.J(a,c);a.Z=new Dlb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.sj)}return a.Z},Qlb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.HF();if(e){var f=g.GF();f&&g.OB(g.Yua)(void 0,e,f,[g.FF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Plb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=m4(f.type,Xlb),p=m4(f.style,Ylb),q=Skb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Ykb;if(null==t)var v=null;else if(g.Ya(t)){l=[];for(var x=g.u(t),B=x.next();!B.done;B=x.next()){var F=f(B.value);
F&&l.push(F)}v=l}else{var G=f(t);v=G?[G]:[]}e=m&&n?new Zkb(m,n,p,v,r):null}else e=null}catch(sa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Mlb(f),L=null;switch(l.type){case "branding":if(f.player.U().ue)break;f.B.element.appendChild(I);L=new D4(I,F4(f),l);break;case "promotion":g.GU(f.player,I,4),L=new Elb(I,F4(f),l)}L&&L.KF();if(f=L)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Ulb(a),g.J(a,a.j));if("card"===e.type){I=a.j;var P=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(P)switch(f=e.tracking||{},f={fX:f.impression,click:f.click,close:f.close,H_:f.teaser_impression,KK:f.teaser_click},l=e.tracking_params||{},L=null,P){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,dj:f,ip:l.card?g.FF(l.card):null,Lj:l.teaser?g.FF(l.teaser):null,Ef:l.icon?g.FF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:o4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};x4(I,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,dj:f,
ip:l.card?g.FF(l.card):null,Lj:l.teaser?g.FF(l.teaser):null,Ef:l.icon?g.FF(l.icon):null,XF:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:o4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};x4(I,c);break;case "productListing":e.signin_url&&(L=o4({target:"current",value:e.signin_url}));P=[];for(var V=e.offers||[],ka=0;ka<V.length;ka++)P.push(new elb(g.ue(V[ka].merchant),
g.ue(V[ka].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,dj:f,ip:l.card?g.FF(l.card):null,Lj:l.teaser?g.FF(l.teaser):null,Ef:l.icon?g.FF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,OC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:o4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Jkb:L,Ikb:e.signin_title?e.signin_title:void 0,Hkb:e.signin_message?e.signin_message:void 0,offers:P,onClickCommand:null};x4(I,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,dj:f,ip:l.card?g.FF(l.card):
null,Lj:l.teaser?g.FF(l.teaser):null,Ef:l.icon?g.FF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,OC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:o4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};x4(I,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,dj:f,ip:l.card?g.FF(l.card):null,Lj:l.teaser?g.FF(l.teaser):null,Ef:l.icon?g.FF(l.icon):null,XF:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:o4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},x4(I,c)}}else jlb(a.j,e);c=!0}}c&&
(Y3(a.player),a.yJ())},Vlb=function(a,b){var c=!1;
a.j||(a.j=Ulb(a),g.J(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(klb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.TT(f)||(c=a.j,d=b.headerText?g.nG(b.headerText):"",g.qf(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.FF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.FF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ef=b.icon.infoCardIconRenderer.trackingParams?g.FF(b.icon.infoCardIconRenderer.trackingParams):null,a.yJ());Y3(a.player)}},Zlb=function(a,b,c,d,e){if(!a.player.U().ue){var f=[];
b.navigationEndpoint&&g.R(b.navigationEndpoint,g.dV)&&g.R(b.navigationEndpoint,g.dV).browseId&&f.push(new Vkb("openUrl","click",new Tkb("/channel/"+g.R(b.navigationEndpoint,g.dV).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.R(b.subscribeButton,
g.MT)){d.channel_id=g.R(b.subscribeButton,g.MT).channelId;var l;b=g.R(b.subscribeButton,g.MT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.nG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.nG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.nG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.nG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.R(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.Q2))?void 0:m.url)||"";l={subscribeText:g.nG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.nG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Zkb(c,"branding","branding",f,d);l=Mlb(a);a.B.element.appendChild(l);f=new D4(l,F4(a),f);f.KF();g.J(f,f);a.K[c]=f}},Rlb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ma.push(g.wu.Si(function(){b.apply(null,g.oa(c))}))}},$lb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.yU.prototype.nB=g.ca(29,function(a,b){var c=g.gW(this.zb());c&&c.nB(a,b)});
var $3={},a4=null;g.ib(c4,g.Yu);g.k=c4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;b4(this);this.startTime=a=g.gb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.qJ();this.Wl("play");this.isPaused()&&this.Wl("resume");this.j=1;var b=g.db(this);b in $3||($3[b]=this);vkb();wkb(this,a);return!0};
g.k.stop=function(a){b4(this);this.j=0;a&&(this.progress=1);xkb(this,this.progress);this.Wl("stop");this.wr()};
g.k.pause=function(){this.isPlaying()&&(b4(this),this.j=-1,this.Wl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Wl("destroy");c4.Lf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.qL=function(){this.Wl("animate")};
g.k.Wl=function(a){this.dispatchEvent(new ykb(a,this))};
g.ib(ykb,g.yb);g.ib(d4,c4);d4.prototype.C=function(){};
d4.prototype.qL=function(){this.C();d4.Lf.qL.call(this)};
d4.prototype.wr=function(){this.C();d4.Lf.wr.call(this)};
d4.prototype.qJ=function(){this.C();d4.Lf.qJ.call(this)};
g.ib(zkb,d4);zkb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Ckb,g.H);g.k=Ckb.prototype;g.k.Ra=function(a,b,c,d){c=(0,g.eb)(c,d||this.B);a=g.OC(a,b,c);this.j.push(a);return a};
g.k.SI=function(a,b,c,d){c=(0,g.eb)(c,d||this.B);a=tkb(a,b,c);this.j.push(a);return a};
g.k.Nc=function(a){g.PC(a);g.Hb(this.j,a)};
g.k.Jf=function(){g.PC(this.j);this.j.length=0};
g.k.xa=function(){this.Jf();g.H.prototype.xa.call(this)};g.w(Fkb,g.RV);g.k=Fkb.prototype;g.k.load=function(){g.RV.prototype.load.call(this);if(!g4(this)){var a=g.dSa(this.player.getVideoData());a?(a=Ekb(a,Gkb(this)),h4(this,a,!1)):Hkb(this)}};
g.k.unload=function(){h4(this,null);this.C&&(this.C.abort(),this.C=null);g.RV.prototype.unload.call(this)};
g.k.Ih=function(a,b){return g4(this)?"loadCustomEndscreenRenderer"===a?(a=Ekb(b,"new"),h4(this,a),!0):null:null};
g.k.getOptions=function(){return g4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Zb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<amb.length;f++){var h=Math.abs(b.width-amb[f]);if(-1===e||d>=h)e=f,d=h}d=bmb[e];this.B&&g.Yr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.hs(e.element,m,f);g.ds(e.element,n,p);g.Pu(e.element,cmb);256<m||256<f?g.Mu(e.element,"ytp-ce-large-round"):96<m||96<f?g.Mu(e.element,"ytp-ce-medium-round"):g.Mu(e.element,"ytp-ce-small-round");g.Pu(e.element,dmb);m=h.left+h.width/2;h=h.top+l/2;g.Mu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Pu(e.element,bmb);g.Mu(e.element,d);(e=g.Ke(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Yr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())l4(this,this.endscreen.impressionUrls),(a=g.HF())&&this.endscreen.visualElement&&g.XF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Mu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Mu(b,"ytp-ce-shown");l4(this,c.impressionUrls);(b=g.HF())&&g.XF(b,c.visualElement);this.player.U().K&&this.player.ib("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Ou(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Ou(b,"ytp-ce-shown");this.player.U().K&&this.player.ib("endscreenelementhidden",a)}};
g.k.W$=function(a){var b=this;a.target===window&&(new g.Eu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Pu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var amb=[346,426,470,506,570,640,853,1280,1920],bmb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),dmb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],cmb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Ukb={zsa:"current",QSa:"new"};var Wkb={CLOSE:"close",tWa:"openUrl",SUBSCRIBE:"subscribe"},Xkb={Oqa:"click",CLOSE:"close",aEa:"hidden",K0a:"rollOut",L0a:"rollOver",v2a:"shown"};Zkb.prototype.df=function(){var a=$kb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Ylb={Fla:"anchored",R0:"branding",CHANNEL:"channel",nsa:"cta",dEa:"highlightText",eIa:"label",PLAYLIST:"playlist",aZa:"popup",u5a:"speech",SUBSCRIBE:"subscribe",d9a:"title",VIDEO:"video",Cfb:"website"},Xlb={R0:"branding",Doa:"card",Dua:"drawer",cEa:"highlight",oOa:"marker",F_a:"promotion",TEXT:"text",hhb:"widget"};g.w(s4,g.H);g.k=s4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.jK(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.Za.set(a,e);this.context.J.Af([a])};
g.k.KF=function(){this.context.B.subscribe("resize",this.WG,this)};
g.k.Fb=function(){return this.element};
g.k.rL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.nf(this.Fb())};
g.k.WG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=n4(a);if(f){var h=glb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Gf||!1,n=g.TB(f||"");m&&n&&(n.v||n.list)?e.context.J.Io(n.v,b,n.list,!1):g.nH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);E4(this.context.logger,c,l,d);flb(f)||(c=g.HF(),d=b.itct,c&&d&&g.$F(c,g.FF(d)))}};
g.k.xa=function(){this.Xa.clear();this.Za.clear();g.H.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.w(ilb,s4);g.k=ilb.prototype;g.k.jt=function(){this.ra&&x4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.is(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.WG=function(){var a=this.isAvailable();g.js(this.Fb(),a);g.Qu(this.context.J.getRootNode(),g.cZ.IV_DRAWER_ENABLED,a);Y3(this.J)};
g.k.destroy=function(){this.J.nB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.NE(this.ma);g.UC(this.Qa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();s4.prototype.destroy.call(this)};
g.k.W4=function(){if(this.C){E4(this.context.logger,B4(this).dj.close);var a=g.HF();a&&this.N&&g.$F(a,this.N);w4(this)}};
g.k.t5=function(){g.Qu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.K7=function(){var a=g.HF(),b=B4(this);b=b?b.Ef:this.Ef;a&&b&&g.YF(a,[b])};
g.k.J7=function(){var a=g.HF(),b=B4(this);b=b?b.Ef:this.Ef;a&&b&&g.ZF(a,[b])};
g.k.C1=function(){var a=B4(this);E4(this.context.logger,a.dj.H_);var b=g.HF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Lj&&c.push(a.Lj);a.Ef&&c.push(a.Ef);0<c.length&&g.YF(b,c)}else g.YF(b,[a.Lj,a.Ef])};
g.k.L7=function(){var a=g.HF(),b=B4(this);a&&b&&g.ZF(a,[b.Lj])};
g.k.B1=function(a){var b=B4(this),c=g.HF();this.j?a?(a=this.context.logger,E4(a,b.dj.KK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Lj&&g.$F(c,b.Lj)):(a=this.context.logger,E4(a,b.dj.KK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ef&&g.$F(c,b.Ef)):(a=this.context.logger,E4(a,b.dj.KK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ef&&g.$F(c,this.Ef))};g.w(C4,s4);C4.prototype.KF=function(){s4.prototype.KF.call(this);ylb(this)};
C4.prototype.show=function(){s4.prototype.show.call(this);var a=g.HF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.YF(a,[g.FF(b.itct)])};
C4.prototype.hide=function(){s4.prototype.hide.call(this);var a=g.HF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ZF(a,[g.FF(b.itct)])};g.w(D4,C4);D4.prototype.eB=function(){g.Mu(this.Fb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.js(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Fb().appendChild(b);var c=this.annotation.df();c&&t4(this,b,c,this.annotation.id,a.session_data);Clb(this,a)};
D4.prototype.show=function(){if(!this.isActive&&(C4.prototype.show.call(this),this.N||(this.eB(),this.N=!0),g.js(this.Fb(),!0),this.isActive=!0,this.B)){try{zlb(this,this.B)}catch(a){}g.Mu(this.context.J.getRootNode(),"ytp-branding-shown")}};
D4.prototype.hide=function(){this.isActive&&(C4.prototype.hide.call(this),g.js(this.Fb(),!1),this.isActive=!1,g.Ou(this.context.J.getRootNode(),"ytp-branding-shown"))};
D4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);C4.prototype.destroy.call(this)};g.w(Elb,C4);g.k=Elb.prototype;
g.k.eB=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Fb().setAttribute("aria-hidden","true");this.Fb().setAttribute("aria-label","Promotion");this.Fb().tabIndex=0;var e=this.annotation.df(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&t4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Mn(f,n4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&t4(this,
this.Fb(),e,this.annotation.id,b.session_data,void 0,c)}g.Mu(this.j,"iv-click-target");e&&t4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Mu(this.j,"iv-click-target"),e&&t4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ra(this.B,"click",function(q){Hlb(a,5E3,q)});
c.appendChild(this.B);g.js(this.B,!1);this.context.j.Ra(this.Fb(),"mouseover",this.J6,this);this.context.j.Ra(this.Fb(),"mouseout",this.I6,this);this.context.j.Ra(this.Fb(),"touchend",function(q){Hlb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ra(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.E6:this.D6,this);c.appendChild(this.C);g.Nu(this.Fb(),d);h&&(g.kf(this.Fb(),h),n&&h.appendChild(n));g.kf(this.Fb(),this.N);g.kf(this.Fb(),c)};
g.k.show=function(){this.isActive||(C4.prototype.show.call(this),this.W||(this.eB(),this.W=!0),g.js(this.Fb(),!0),g.ag(function(){g.Ou(this.Fb(),"iv-promo-inactive")},100,this),this.Fb().removeAttribute("aria-hidden"),this.isActive=!0,Jlb(this),Flb(this),Glb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Mu(this.Fb(),"iv-promo-inactive"),this.isActive=!1,this.Fb().setAttribute("aria-hidden","true"))};
g.k.rL=function(a,b,c,d,e,f){return this.isCollapsed?!1:C4.prototype.rL.call(this,a,b,c,d,e,f)};
g.k.J6=function(a){this.Z=!0;Hlb(this,500,a)};
g.k.I6=function(){this.Z=!1;Ilb(this)};
g.k.D6=function(a){a.stopPropagation();this.hide()};
g.k.E6=function(a){a.stopPropagation();Jlb(this);this.isCollapsed=!0;g.Mu(this.Fb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();C4.prototype.destroy.call(this)};g.w(Llb,g.RV);g.k=Llb.prototype;g.k.Ih=function(a,b){if(!$lb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.w2(b))&&Qlb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(mlb(this.j,b),Y3(this.player)),!0}return null};
g.k.getOptions=function(){return $lb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.mu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.gU(b)||g.rU(this.player.app)?!1:1===c&&!b.yU||a.Na.get(b.videoId)||g.UT(b)||g.eSa(b)?!0:!1};
g.k.yJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.hs(this.C.element,a.width,a.height);g.ds(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Qk();a=this.j;b=b.width;g.Qu(a.D,"iv-drawer-small",426>=b);g.Qu(a.D,"iv-drawer-big",1280<=b)}};
g.k.D1=function(a){Nlb(this,a.state);g.TG(a.state,2)&&(this.Ik()&&this.gp()&&2!==this.player.getPresentingPlayerType()&&this.oB(!1),this.nB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.$B(h)&&h.responseXML?h.responseXML:null)&&(Qlb(b,h),g.Mu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.RV.prototype.load.call(this);Nlb(this,this.player.Vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.mD()&&(a=Rlb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Slb(e,f);f=f&&(f.IM||f.bH);if(!c.zx||f)c.Xa?Olb(this,c.Xa,e):(this.vx=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.TT(h))&&!b.W&&Wlb(b,h)},this.player.addEventListener("videodatachange",this.vx));
g.GU(this.player,this.C.element,4);this.yJ();(f=g.UT(c))&&Vlb(this,f);(f=g.eSa(c))&&f.featuredChannel&&Zlb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Sg=g.Me("ytp-cards-button",this.player.getRootNode());g.TT(c)&&Wlb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Olb(this,b.Xa,a)};
g.k.unload=function(){this.player.wf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,Y3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.W=!1;this.K={};this.B.hide();g.RV.prototype.unload.call(this);this.C.detach();this.vx&&(this.player.removeEventListener("videodatachange",this.vx),this.vx=null)};
g.k.fZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Tlb(this):this.load())};
g.k.Ik=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.W};
g.k.gp=function(){return!!this.j&&this.j.C};
g.k.oB=function(a,b,c){b=void 0===b?!1:b;this.Ik();this.j&&(a?c?v4(this.j,c,b):v4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):w4(this.j))};
g.k.nB=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.fZ,this);g.Ou(this.player.getRootNode(),g.cZ.IV_DRAWER_OPEN);for(var a=this.ma,b=g.wu,c=0,d=a.length;c<d;c++)b.Oj(a[c]);this.ma.length=0;g.RV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.QV("annotations_module",Llb);g.QV("creatorendscreen",Fkb);})(_yt_player);
