(function(g){var window=this;'use strict';var gqb=function(a,b){a.ib("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.Qu(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Wg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.ZS&&(b.lengthText?(e=b.lengthText||null,f=b.lw||null):b.lengthSeconds&&(e=g.cH(b.lengthSeconds),f=g.cH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.xQa(d).type;var l=b instanceof g.ZS?b.isLivePlayback:null,m=b instanceof g.ZS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.qK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Rk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.us};b instanceof g.YS&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.U(),c=b.D;
g.U.call(this,{I:"a",S:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},V:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",
Ma:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",ya:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ya:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ya:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ya:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},l6=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.U({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.J(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",S:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ya:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.W:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},V:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",ya:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",ya:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",ya:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",ya:"{{author_and_views}}"}]}]}]});
g.J(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ha("ytp-autonav-endscreen-link-container"),"click",this.KS);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",S:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.U({I:"div",S:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.U({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancel autoplay"},ya:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.Ra("click",this.K1,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},ya:"Play Now"});g.J(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.Ra("click",this.KS,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&hqb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Eu(function(){iqb(c)},
500);
g.J(this,this.D);this.JS();this.T(a,"autonavvisibility",this.JS);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.J1),this.T(a,"onAutonavCoundownStarted",this.C8))},m6=function(a){var b=a.J.Qk(!0,a.J.isFullscreen());
g.Qu(a.container.element,"ytp-autonav-endscreen-small-mode",a.Vf(b));g.Qu(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.DK);g.Qu(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.rf());g.Qu(a.J.getRootNode(),"countdown-running",a.Vk());g.Qu(a.container.element,"ytp-player-content",a.J.rf());g.Yr(a.overlay.element,{width:b.width+"px"});if(!a.Vk()){a.J.rf()?jqb(a,Math.round(kqb(a)/1E3)):jqb(a);b=!!a.suggestion&&!!a.suggestion.us;var c=a.J.rf()||!b;
g.Qu(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Qu(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.jG(a.B,a.J.rf());g.Qu(a.element,"ytp-enable-w2w-color-transitions",lqb(a))}},iqb=function(a){var b=kqb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);jqb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Vk()?a.select(!0):a.Vk()&&a.D.start()},kqb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.QB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Os()?a.J.Os():g.EJ(a.J.U().experiments,"autoplay_time")||1E4},hqb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.v5;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},lqb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},jqb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ha("ytp-autonav-endscreen-upnext-header");g.lf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.jf("Up next in $SECONDS".slice(0,d)));var e=g.$e("span");g.Ku(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.qf(e,b);a.appendChild(e);a.appendChild(g.jf("Up next in $SECONDS".slice(d+c.length)));return}}g.qf(a,"Up next")},n6=function(a,b){g.U.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.U.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",ya:"Up Next"},{I:"span",S:"ytp-upnext-title",ya:"{{title}}"},{I:"span",S:"ytp-upnext-author",ya:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
ya:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ha("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Eu(this.gH,5E3,this);this.B=0;var b=this.Ha("ytp-upnext-cancel");this.cancelButton=new g.U({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel autoplay"},ya:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Ra("click",this.L1,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.J(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ha("ytp-upnext-autoplay-icon");this.T(b,"click",this.M1);this.api.createClientVe(b,this,115130);this.LS();this.T(a,"autonavvisibility",this.LS);this.T(a,"mdxnowautoplaying",this.o9);this.T(a,"mdxautoplaycanceled",this.p9);g.Qu(this.element,"ytp-upnext-mobile",this.api.U().B)},mqb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.QB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Os()?a.api.Os():g.EJ(a.api.U().experiments,"autoplay_time")||1E4},nqb=function(a,b){b=mqb(a,b);
var c=Math,d=c.min;var e=(0,g.FD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Vk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Vk()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ya:"More videos"}]});this.N=new g.U({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l6(this.player);g.J(this,this.B);this.B.Ja(this.element);a.getVideoData().Nf?this.j=this.B:(this.j=new o6(a),g.GU(this.player,this.j.element,4),g.J(this,this.j));this.overlay=new g.U({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.aL(this);g.J(this,this.D);g.J(this,this.table);this.table.Ja(this.element);this.table.show();g.J(this,this.N);this.N.Ja(this.table.element);this.hide()},q6=function(a){var b=a.rf();
b!==a.G&&(a.G=b,a.player.oa("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r6=function(a,b){g.U.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],ya:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.m_();2===this.buttonType&&g.Mu(this.element,"ytp-continue-watching-button");this.Ra("click",this.onClick);this.Ra("videodatachange",this.m_);g.jG(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.ye=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r6(a,2);g.J(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},oqb=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",ya:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.J(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.yW("Subscribe",null,"Unsubscribe",null,!0,!1,b.El,b.subscribed,"trailer-endscreen",null,a,!1);g.J(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ha("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Sa);this.Sa();this.hide()},t6=function(a){var b=a.U(),c=g.YK||g.lS?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Ma:e,Y:{href:"{{url}}",target:d?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",Y:c,V:[{I:"span",S:"ytp-videowall-still-info-title",ya:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",ya:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",ya:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",ya:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",ya:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",ya:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.aL(this);g.J(this,this.j);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.W=null;this.B=new g.aL(this);g.J(this,this.B);this.K=new g.Eu(function(){g.Mu(b.element,"ytp-show-tiles")},0);
g.J(this,this.K);var c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},V:[g.pG()]});g.J(this,c);c.Ja(this.element);c.Ra("click",this.Q1,this);this.table=new g.gG({I:"div",S:"ytp-endscreen-content"});g.J(this,this.table);this.table.Ja(this.element);c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},V:[g.qG()]});g.J(this,c);c.Ja(this.element);c.Ra("click",this.P1,this);a.getVideoData().Nf?this.j=new l6(a,!0):this.j=new o6(a);
g.J(this,this.j);g.GU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v6=function(a){return g.HU(a.player)&&a.LC()&&!a.D},w6=function(a){var b=a.rf();
b!==a.N&&(a.N=b,a.player.oa("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.J(this,this.watchButton);this.watchButton.Ja(this.element);g.Geb(a)&&(this.j=new g.y2(a),g.J(this,this.j),this.B=new g.U({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},V:[this.j]}),g.J(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},sqb=function(a){g.RV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.aL(this);g.J(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.FC(g.uS(c))&&d&&!g.CU(a)?(this.B=!0,this.endScreen=new s6(a,g.tU(a))):g.DU(a)?this.endScreen=new x6(a):pqb(a)?(this.D=!0,qqb(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.nh?this.endScreen=new oqb(a):this.endScreen=new n6(a);g.J(this,this.endScreen);g.GU(a,this.endScreen.element,4);rqb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.kK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.lK("endscreen"),function(e){b.onCueRangeExit(e)})},qqb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Gl&&a.C===b.Nf)return!1;a.j=b.Gl;a.C=b.Nf;return!0},pqb=function(a){a=a.U();
return a.Bd&&!a.nh},rqb=function(a){a.player.wf("endscreen");
var b=a.player.getVideoData();b=new g.jK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.jK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Af([b,c])};
g.yU.prototype.Os=g.ca(16,function(){return this.app.Os()});
g.X0.prototype.Os=g.ca(15,function(){return this.getVideoData().sU});
g.uU.prototype.qo=g.ca(14,function(a){this.wi().qo(a)});
g.XW.prototype.qo=g.ca(13,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.dY.prototype.qo=g.ca(12,function(a){this.overflowButton&&this.overflowButton.qo(a)});
g.uU.prototype.uo=g.ca(11,function(a){this.wi().uo(a)});
g.bX.prototype.uo=g.ca(10,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.dY.prototype.uo=g.ca(9,function(a){this.shareButton&&this.shareButton.uo(a)});
g.uU.prototype.fu=g.ca(8,function(a){this.wi().fu(a)});
g.rW.prototype.fu=g.ca(7,function(a){this.yQ!==a&&(this.yQ=a,this.kq())});
g.uU.prototype.du=g.ca(6,function(a){this.wi().du(a)});
g.dY.prototype.du=g.ca(5,function(a){this.xQ!==a&&(this.xQ=a,this.jq())});g.w(k6,g.U);k6.prototype.select=function(){this.J.Io(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.eD||void 0)&&this.J.logClick(this.element)};
k6.prototype.onClick=function(a){g.ZU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(l6,g.U);g.k=l6.prototype;g.k.pG=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.Rk()),m6(this))};
g.k.Vk=function(){return 0<this.C};
g.k.xB=function(){this.Vk()||(this.C=Date.now(),iqb(this),gqb(this.J,kqb(this)),g.Qu(this.J.getRootNode(),"countdown-running",this.Vk()))};
g.k.Nw=function(){this.eq();iqb(this);var a=this.j.Ha("ytp-autonav-endscreen-upnext-header");a&&g.qf(a,"Up next")};
g.k.eq=function(){this.Vk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.eq()};
g.k.KS=function(a){g.ZU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ha("ytp-autonav-endscreen-link-container")&&(a=this.j.Ha("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.ib("innertubeCommand",this.K),this.eq()):this.select())};
g.k.K1=function(){this.J.logClick(this.cancelButton.element);g.AU(this.J,!0);this.G&&this.J.ib("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&hqb(this,b);var c;this.G=null==(c=b.o5)?void 0:c.command};
g.k.C8=function(a){if(lqb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.kH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.kH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.kH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.kH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.kH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.kH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Qu(this.element,"ytp-w2w-animate",!0)}};
g.k.J1=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.Qu(this.element,"ytp-w2w-animate",!1)};
g.k.JS=function(){var a=this.J.rf();this.N&&this.Ib!==a&&g.jG(this,a);m6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ha("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Vf=function(a){return 400>a.width||459>a.height};g.w(n6,g.U);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.LC=function(){return!1};
g.k.rf=function(){return!1};
g.k.xX=function(){return!1};g.w(o6,g.U);g.k=o6.prototype;g.k.gH=function(){this.notification&&(this.D.stop(),this.Nc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.pG=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.LS=function(){g.jG(this,this.api.rf());this.api.logVisibility(this.element,this.api.rf());this.api.logVisibility(this.Ha("ytp-upnext-autoplay-icon"),this.api.rf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.rf())};
g.k.x9=function(){window.focus();this.gH()};
g.k.xB=function(a){var b=this;this.Vk()||(g.OE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.FD)(),this.j=new g.Eu(function(){nqb(b,a)},25),nqb(this,a),gqb(this.api,mqb(this,a)));
g.Ou(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Vk=function(){return!!this.j};
g.k.Nw=function(){this.eq();this.B=(0,g.FD)();nqb(this);g.Mu(this.element,"ytp-upnext-autoplay-paused")};
g.k.eq=function(){this.Vk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.gH(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Wg()}),this.C=this.T(this.notification,"click",this.x9),this.D.start())}this.eq();this.api.nextVideo(!1,a)};
g.k.M1=function(a){!g.pf(this.cancelButton.element,a.target)&&g.ZU(a,this.api)&&(this.api.rf()&&this.api.logClick(this.Ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.L1=function(){this.api.rf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.AU(this.api,!0)};
g.k.o9=function(a){this.api.getPresentingPlayerType();this.show();this.xB(a)};
g.k.p9=function(){this.api.getPresentingPlayerType();this.eq();this.hide()};
g.k.xa=function(){this.eq();this.gH();g.U.prototype.xa.call(this)};g.w(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.D.T(this.player,"appresize",this.YB);this.D.T(this.player,"onVideoAreaChange",this.YB);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.MS);this.D.T(this.player,"onAutonavCancelled",this.N1);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.AU(this.player,!1);g.HU(this.player)&&this.LC()&&!this.C?(q6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.xB():3===this.videoData.autonavState&&this.j.Nw()):(g.AU(this.player,!0),q6(this));this.YB()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.Nw();q6(this)};
g.k.YB=function(){var a=this.player.Qk(!0,this.player.isFullscreen());q6(this);m6(this.B);g.Qu(this.element,"ytp-autonav-cancelled-small-mode",this.Vf(a));g.Qu(this.element,"ytp-autonav-cancelled-tiny-mode",this.JI(a));g.Qu(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Yr(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Qu(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.zT(this.videoData);b&&(this.j.pG(b),this.j!==this.B&&this.B.pG(b))}if(a&&a.length)for(b=0;b<tqb.length;++b){var c=tqb[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.J(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.YB()}};
g.k.MS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.eq(),this.Ib&&this.YB()):(this.K=!0,this.rf()&&(2===a?this.j.xB():3===a&&this.j.Nw()))};
g.k.N1=function(a){a?this.MS(1):(this.C=null,this.K=!1)};
g.k.LC=function(){return 1!==this.videoData.autonavState};
g.k.Vf=function(a){return(910>a.width||459>a.height)&&!this.JI(a)&&!(400>=a.width||360>=a.height)};
g.k.JI=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.rf=function(){return this.Ib&&g.HU(this.player)&&this.LC()&&!this.C};
var tqb=[1,3,2,4];g.w(r6,g.U);g.k=r6.prototype;g.k.m_=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.$U(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.mS(b)){var c={};g.mS(b)&&g.nU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.KP(c,b);a=g.Ml(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Ib&&this.Z)};
g.k.show=function(){g.U.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.logVisibility()};
g.k.Hc=function(a){g.U.prototype.Hc.call(this,a);this.logVisibility()};g.w(s6,n6);s6.prototype.show=function(){3!==this.player.getPlayerState()&&(n6.prototype.show.call(this),this.ye.du(!0),this.ye.uo(!0),this.J.U().Pe||this.ye.qo(!0),this.J.logVisibility(this.element,!0),this.watchButton.Hc(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.ye.du(!1);this.ye.uo(!1);this.ye.qo(!1);this.J.logVisibility(this.element,!1);this.watchButton.Hc(!1)};g.w(oqb,n6);oqb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.El;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(t6,g.U);t6.prototype.select=function(){this.api.Io(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.eD||void 0)&&this.api.logClick(this.element)};
t6.prototype.onClick=function(a){if(g.mS(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Rk(),c={};g.USa(this.api,c,"emb_rel_end");b=g.Ml(b,c);g.$U(b,this.api,a)}else g.ZU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Gf?!1:b.D};g.w(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.qq();this.B.T(this.player,"appresize",this.qq);this.B.T(this.player,"onVideoAreaChange",this.qq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.uL);this.B.T(this.player,"onAutonavCancelled",this.O1);a=this.videoData.autonavState;a!==this.W&&this.uL(a);this.B.T(this.element,"transitionend",this.M$)};
g.k.destroy=function(){g.UC(this.B);g.vb(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.Ou(this.element,"ytp-show-tiles");this.K.stop();this.W=this.videoData.autonavState};
g.k.LC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Ib;n6.prototype.show.call(this);g.Ou(this.element,"ytp-show-tiles");this.player.U().B?g.Gu(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.AU(this.player,!1);v6(this)?(w6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.xB():3===this.videoData.autonavState&&this.j.Nw()):(g.AU(this.player,!0),w6(this));a!==this.Ib&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Ib;n6.prototype.hide.call(this);this.j.Nw();w6(this);a!==this.Ib&&this.player.logVisibility(this.element,!1)};
g.k.M$=function(a){a.target===this.element&&this.qq()};
g.k.qq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.zT(d)];if(e.length){g.Mu(this.element,"ytp-endscreen-paginate");var f=this.J.Qk(!0,this.J.isFullscreen());if(a=g.tU(this.J))a=a.Og()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.hs(f,n,p);g.Yr(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.pG(g.zT(this.videoData));this.j instanceof
l6&&m6(this.j);g.Qu(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.je(q+this.C,c),0!==t){r=this.stills[h];r||(r=new t6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var x=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-v-4,F=Math.floor(n*(l+t)/a)-x-4;g.ds(r.element,x,v);g.hs(r.element,F,B);g.Yr(r.element,"transitionDelay",
(m+l)/20+"s");g.Qu(r.element,"ytp-videowall-still-mini",1===t);g.Qu(r.element,"ytp-videowall-still-large",2<t);t=Math.max(F,B);g.Qu(r.element,"ytp-videowall-still-round-large",256<=t);g.Qu(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.Qu(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.Lu(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,v),g.mS(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Rk(),v={},g.nU(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.Ml(t,g.KP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.Qu(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.nf(a.element),g.ub(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.qq())};
g.k.P1=function(){this.C+=this.stills.length;this.qq()};
g.k.Q1=function(){this.C-=this.stills.length;this.qq()};
g.k.xX=function(){return this.j.Vk()};
g.k.uL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.eq(),this.Ib&&this.qq()):(this.G=!0,this.Ib&&v6(this)&&(2===a?this.j.xB():3===a&&this.j.Nw()))};
g.k.O1=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.uL(1)}else this.D=null,this.G=!1;this.qq()};
g.k.rf=function(){return this.Ib&&v6(this)};g.w(x6,n6);x6.prototype.SD=function(){var a;return null==(a=this.j)?void 0:a.SD()};
x6.prototype.show=function(){if(3!==this.player.getPlayerState()){n6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.SD();g.Qu(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.tU(this.player))||c.fu(!0);this.player.logVisibility(this.element,!0);this.watchButton.Hc(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;null==(a=g.tU(this.player))||a.fu(!1);this.player.logVisibility(this.element,!1);this.watchButton.Hc(!1)};g.w(sqb,g.RV);g.k=sqb.prototype;g.k.mu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.DU(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.zT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!pqb(this.player)||d;a=a.yj;c=this.player.rD();return d&&!a&&!c&&!b};
g.k.rf=function(){return this.endScreen.rf()};
g.k.r7=function(){return this.rf()?this.endScreen.xX():!1};
g.k.xa=function(){this.player.wf("endscreen");g.RV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.zb().Fe.get("heartbeat"),d=g.zT(a);!d||b.videoId!==d.videoId||a.wS?(this.player.Io(b.videoId,void 0,void 0,!0,!0,b),c&&c.TI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.RV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.RV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.mu()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){rqb(this);this.D&&qqb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.J(this,this.endScreen),g.GU(this.player,this.endScreen.element,4))};g.QV("endscreen",sqb);})(_yt_player);
